---
workflow:
  - deploy

shared:
  image: node:8

jobs:
  main:
    steps:
      - install-dependencies: npm install
      - test: npm test
  deploy:
      steps:
        - install_packer: . ./config/install_packer.sh
        - hello: echo hello
