---
shared:
  image: node:8
  environment:
    AWS_DEFAULT_REGION: us-west-2

jobs:
  main:
    steps:
      - build_depends: . ./config/setup.sh
      - install-dependencies: npm install
      - unit_test: npm test
      - packer_validate: packer validate config/packer.json
      - packer_build: . ./config/packer_build.sh
      - deploy: . ./config/deploy.sh
      - func_test: HOST=`/opt/sd/meta get public_dns` npm run functional
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - SEC_GROUP
      - SUBNET
      - SAUCE_KEY
      - SAUCE_USER
