---
workflow:
  - package
  - deploy
  - test_it

shared:
  image: node:8

jobs:
  main:
    steps:
      - install-dependencies: npm install
      - test: npm test
  package:
    steps:
      - install_packer: . ./config/install_packer.sh
      - packer_validate: packer validate config/packer.json
      - packer_build: . ./config/packer_build.sh
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
  deploy:
    image: python:2
    environment:
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - install_awscli: pip install --upgrade awscli
      - test_awscli: aws --version
      - deploy: . ./config/deploy.sh
    secrets:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - SEC_GROUP
      - SUBNET
  test_it:
    steps:
      - install-dependencies: npm install
      - test: npm run functional
    secrets:
      - SAUCE_KEY
      - SAUCE_USER
