---
workflow:
  - deploy

shared:
  image: node:8

jobs:
  main:
    steps:
      - assert_aptget: apt-get update
      - assert_install: apt-get install unzip
      - install-dependencies: npm install
      - test: npm test
  deploy:
      steps:
        - install_packer: . ./config/install_packer.sh
        - hello: echo hello
